site_name: Smart City IoT
site_description: Documentation du projet Smart City IoT
site_author: Aurélie
docs_dir: docs

theme:
  name: material
  language: fr

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            show_root_heading: true
            show_source: true
            members_order: source

nav:
  - Accueil: api/index.md
  - Rapport incident:
      - Juin: api/reports/june_incident.md
  - Référence technique: api/reference.md
  - Contrat API: api/api-spec.md