apiVersion: 1

contactPoints:
  - orgId: 1
    name: WeebhookSite
    receivers:
      - uid: webhook-site-01
        type: webhook
        settings:
          url: https://webhook.site/110f8c60-1e1f-4cc1-851b-b2a193c1b5c6
          httpMethod: POST

policies:
  - orgId: 1
    receiver: WeebhookSite
    group_by: ['grafana_folder', 'alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: WeebhookSite
        object_matchers:
          - ['Severity', '=', 'Critical']

providers:
  - name: 'Alert Rules Provider'
    orgId: 1
    folder: UrbanHub
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/provisioning/alerting/alerts.yml