name: CI Documentation

on:
  push:
    branches:
      - Refacto

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Crucial pour que Mike lise l'historique de gh-pages

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installer les dépendances
        run: |
            python -m pip install --upgrade pip
            # Ajout de pika dans la liste
            pip install pytest pytest-cov mkdocs-material mike pydantic fastapi httpx pika

      - name: Exécuter le test interactif (Doctest)
        run: |
          cd services/validation-service
          # Le "-c /dev/null" désactive la lecture du pyproject.toml pour ce test
          python -m pytest -c /dev/null --doctest-glob="ma-doc-diataxis/docs/**/*.md"
        env:
          PYTHONPATH: ./services/validation-service

      - name: Configurer Git pour Mike
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Déployer la documentation avec Mike
        run: |
          # On se place là où se trouve ton mkdocs.yml
          cd services/validation-service/ma-doc-diataxis
          
          # On s'assure que Mike récupère la branche gh-pages existante pour ne pas l'écraser
          git fetch origin gh-pages:gh-pages || true
          
          # Compilation et push
          python -m mike deploy latest "Version Actuelle" --update-aliases --push